name: Compile snapshot with Maven

on:
  push:
    branches-ignore:
      - master
      - development
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://repo.andrei1058.dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Deploy snapshot with Maven
        env:
          MVN_REPO_USER: ${{ secrets.MVN_REPO_USER }}
          MVN_REPO_PASS: ${{ secrets.MVN_REPO_PASS }}
          ANDEV_RES_ID: 1
        run: |
          sudo apt install jq -y
          curl -X GET https://api.andrei1058.dev/v1/resources/$ANDEV_RES_ID/versioning/current -H "Accept: application/json" >> version.json
          export UPDATE_VERSION=`jq '.version' version.json | tr -d '"'`
          mvn versions:set -DnewVersion=$UPDATE_VERSION-SNAPSHOT
          mvn versions:update-child-modules
          mvn clean install -s ci_settings.xml
          echo "UPDATE_VERSION=$UPDATE_VERSION" >> $GITHUB_ENV
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./
          # The desired behavior if no files are found using the provided path.
